In [1]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
print("Type of array:",a.dtype)

Type of array: int64


In [4]:
print("Shape of the array:",a.shape)

Shape of the array: (10,)


In [5]:
print("Size of the array:",a.size)

Size of the array: 10


In [6]:
print("Dimension of the array:",a.ndim)

Dimension of the array: 1


In [7]:
print("Length of the array:",len(a))

Length of the array: 10


In [8]:
print("Reversed array:",a[::-1])

Reversed array: [10  9  8  7  6  5  4  3  2  1]


In [9]:
print("Sliced array:",a[2:8])

Sliced array: [3 4 5 6 7 8]


In [10]:
print("Elements greater than 5 in the array:",a[a>5])

Elements greater than 5 in the array: [ 6  7  8  9 10]


In [20]:
ar=np.array([[3,1,4],[4,2,9],[10,6,2],[11,2,5]])
print("Original array:\n",ar)

Original array:
 [[ 3  1  4]
 [ 4  2  9]
 [10  6  2]
 [11  2  5]]


In [21]:
print("Reshaped array:\n",ar.reshape(4,3))

Reshaped array:
 [[ 3  1  4]
 [ 4  2  9]
 [10  6  2]
 [11  2  5]]


In [22]:
print("Sorted array:\n",np.sort(ar))

Sorted array:
 [[ 1  3  4]
 [ 2  4  9]
 [ 2  6 10]
 [ 2  5 11]]


In [25]:
print("Sliced array:\n",ar[2:6])

Sliced array:
 [[10  6  2]
 [11  2  5]]


In [26]:
print("Extracted 1st column:\n",ar[:,0])

Extracted 1st column:
 [ 3  4 10 11]


In [28]:
print("Extracted 1st row:\n",ar[0,:])

Extracted 1st row:
 [3 1 4]
