In [2]:
import numpy as np
a=np.array([10,20,30,40,50])
print("One dimensional array:",a)

One dimensional array: [10 20 30 40 50]


In [4]:
import numpy as np
b=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("Two dimensional array:",b)

Two dimensional array: [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [5]:
import numpy as np
c=np.zeros((3,5))
print("\n Array with all zeros:\n",c)


 Array with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
import numpy as np
d=np.random.random((3,3))
print("\n Random value:\n",d)


 Random value:
 [[0.35507195 0.81209456 0.8294121 ]
 [0.77540669 0.63444027 0.34330152]
 [0.32895178 0.86875831 0.01788786]]


In [8]:
import numpy  as np
e=np.arange(0,100,5)
print("\n Range value:\n",e)


 Range value:
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [9]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr=arr.reshape((4,3))
print("\n Original array:\n",arr)
print("\n Reshaped array [4,3]:\n", newarr)


 Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Reshaped array [4,3]:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [1]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print("The array is:",a)

The array is: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [2]:
import numpy as np
a=np.zeros((5,3))
print("Array with all zeroes:\n",a)

Array with all zeroes:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
import numpy as np
a=np.random.random((5,3))
print("Array with random numbers:\n",a)

Array with random numbers:
 [[0.89765037 0.23126756 0.20802793]
 [0.26495307 0.78401192 0.5908731 ]
 [0.28072401 0.0358633  0.3588697 ]
 [0.88822113 0.45690415 0.40477484]
 [0.83363982 0.26844132 0.77404367]]


In [5]:
import numpy as np
a=np.arange(0,10,1)
print("Array with step values:\n",a)

Array with step values:
 [0 1 2 3 4 5 6 7 8 9]


In [7]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
b=a.reshape((3,5))
print("Original array:\n",a)
print("\nReshaped array:\n",b)

Original array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

Reshaped array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [10]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
flat=a.flatten()
print("Flattened array:\n",flat)

Flattened array:
 [1 2 3 4 5 6]


In [11]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print("Number of dimensions:",a.ndim)

Number of dimensions: 2


In [12]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print("Shape of array:",a.shape)

Shape of array: (2, 3)


In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print("Array element type:",a.dtype)

Array element type: int32


In [3]:
import numpy as np
a=np.array([1,2,3,4,5])
b=a.astype('f')
print("Convert array element:",b)
print("Converted array:",b.dtype)

Convert array element: [1. 2. 3. 4. 5.]
Converted array: float32


In [5]:
import numpy as np
a=np.array([1,2,3,4,5])
print("Size of the array:",a.size)

Size of the array: 5
