In [6]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
s1=a[2:6]
print(s1)

[3 4 5 6]


In [9]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
s2=a[::2]
print(s2)

[1 3 5 7 9]


In [10]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
rev=a[::-1]
print(rev)

[9 8 7 6 5 4 3 2 1]


In [15]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
sub=a[0:2,1:3]
print(sub)

[[2 3]
 [6 7]]


In [17]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
fc=a[:,0]
print(fc)

[1 5]


In [20]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
sr=a[1,:]
print(sr)

[5 6 7 8]


In [21]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a[0,0])
print(a[1,2])

1
7


In [24]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[1])

2


In [25]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[-1])

9


In [26]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[1:4])

[2 3 4]


In [27]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[a>5])

[6 7 8 9]


In [30]:
import numpy as np
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
res=np.hstack((a1,a2))
print(res)

[[1 2 5 6]
 [3 4 7 8]]


In [31]:
import numpy as np
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
res=np.vstack((a1,a2))
print(res)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [35]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
sp=np.split(a,2)
print(sp)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [36]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
sp=np.array_split(a,2)
print(sp)

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9])]
