In [1]:
import numpy as np
a1=[20,40,50,70,10]
a2=[6,2,9,7,1]
a=np.array(a1)
b=np.array(a2)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a.dot(b))
sclr=3
print("Result:",a*sclr)

[20 40 50 70 10]
[6 2 9 7 1]
[26 42 59 77 11]
[14 38 41 63  9]
[120  80 450 490  10]
[ 3.33333333 20.          5.55555556 10.         10.        ]
1150
Result: [ 60 120 150 210  30]


In [2]:
import numpy as np
a=np.array([[10,20],[30,40]])
b=np.array([[3,7],[5,9]])
print(a%b)


[[1 6]
 [0 4]]


In [17]:
def myfunc(x,y):
    if x>y:
        return x-y
    else:
        return x+y
import numpy as np
a1=[10,7,2]
a2=[6,5,3]
vectfunc=np.vectorize(myfunc)
print("Array 1:",a1)
print("Array 2:",a2)
print("Result:",vectfunc(a1,a2))

Array 1: [10, 7, 2]
Array 2: [6, 5, 3]
Result: [4 2 5]
